---
  - name: clear lvremove lv root
    shell: lvremove /dev/vg_root/lv_root -y

  - name: vgremove vg root
    shell: vgremove /dev/vg_root

  - name: pvremove sdb
    shell: pvremove /dev/sdb

  - name: lvcreate LogVolHome
    shell: lvcreate -n LogVol_Home -L 2G /dev/VolGroup00

  - name: mkfs xfs LogVol Home
    shell: mkfs.xfs /dev/VolGroup00/LogVol_Home

  - name: mount home mnt
    shell: mount /dev/VolGroup00/LogVol_Home /mnt/

  - name: copy home new directory
    shell: cp -aR /home/* /mnt/

#######replace ssh authorized keys

  - name: replace ssh auth keys
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '.ssh/authorized_keys'
      line: 'AuthorizedKeysFile      /opt/.ssh/authorized_keys'

  - name: reconfig systemctl reconfigure
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: 'PasswordAuthentication no'
      line: 'PasswordAuthentication yes'

  - name: create direct
    file:
      path: /opt/.ssh/
      state: directory

  - name: copy auth key
    copy:
      src: /home/vagrant/.ssh/authorized_keys
      dest: /opt/.ssh/authorized_keys
      remote_src: yes

  - name: restart sshd
    service: name=sshd state=restarted

####### continue dz

  - name: rm rf home old
    shell: rm -rf /home/* && umount /mnt/ && mount /dev/VolGroup00/LogVol_Home /home/

  - name: echo fstab cool command
    shell: echo "`blkid | grep Home | awk '{print $2}'` /home xfs defaults 0 0" >> /etc/fstab

  - name: touch files
    shell: touch /home/file{1..20}

  - name: look touch files
    command: ls -lah /home/
    register: ls
  - debug: var=ls.stdout_lines

  - name: create snapshot home
    shell: lvcreate -L 100MB -s -n home_snap /dev/VolGroup00/LogVol_Home

  - name: experiment rm f files
    shell: rm -f /home/file{11..20}

  - name: look touch files
    command: ls -lah /home/
    register: ls
  - debug: var=ls.stdout_lines

#  - name: umount home
#    shell: umount /home/ && lvconvert --merge /dev/VolGroup00/home_snap && mount /home/
#
#  - name: restore snapshot home
#    shell: lvconvert --merge /dev/VolGroup00/home_snap
#  - name: mount home
#    shell: mount /home/

#  - name: look touch files
#    command: ls -lah /home/
#    register: ls
#  - debug: var=ls.stdout_lines

#### restore ssh
  - name: restore
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '/opt/.ssh/authorized_keys'
      line: 'AuthorizedKeysFile      .ssh/authorized_keys'

  - name: reboot
    command: nohup bash -c "sleep 2s && reboot" &
    async: 1
    poll: 0
    ignore_errors: true

  - name: wait for system online
    wait_for_connection:
      delay: 15
